platform:
- x64
- x86
environment:
  nodejs_version: "6"
  GITHUB_TOKEN:
    secure: 8Wdonhsn/v6+fV2+F7ppIt5Sa0PuoYhWxJ8du0/icd3fwJG+XDy92jBJ36i6KKuo

cache:
- '%APPDATA%\npm-cache'
- '%USERPROFILE%\.electron'
- node_modules
branches:
  only:
  - master
install:
- cd quiz-master
- ps: $configFile = "package.json"
- ps: $j = Get-Content $configFile | ConvertFrom-Json
- ps: $j.name = $j.name+"$env:platform"
- ps: $j | ConvertTo-Json | set-content $configFile
- ps: echo Get-Content $configFile 
- ps: Install-Product node $env:nodejs_version $env:platform
- set PATH=%APPDATA%\npm;%PATH%
- npm install
- npm update

test_script:
- node --version
- npm --version
- npm run make

build_script:
- npm run publish
