#lets see how this works | creates to build jobs 
matrix:
  include:
    #android app 
    - language: generic
      node_js:
        - 6.9.1
      sudo: true
      branches:
        only:
          - master
      install:
        - sudo apt-get install npm
        - cd quiz-master
        - sudo npm install -g n
        - sudo n stable
        #- sudo npm install
        - sudo npm install electron-builder --save-dev
      script:
        #- sudo cordova prepare
        - npm run dist
        - electron-builder -mwl
        - npm run dist -mwl
      release:
        - exit 0
      before_deploy:
        - echo "begin the coping"
        - cp -R "/home/travis/build/voxsar/igenius/quiz-master/dist/Quiz-Master-0.0.1-x86_64.AppImage" $TRAVIS_BUILD_DIR
      deploy:
        provider: releases
        skip-cleanup: true
        api_key:
          secure: $GITHUB_TOKEN # Set in travis-ci.org dashboard, marked secure GITHUB_TOKEN
        file: $TRAVIS_BUILD_DIR/Quiz-Master-0.0.1-x86_64.AppImage
        name: "$TRAVIS_TAG"
        body: "## $TRAVIS_TAG
              version $TRAVIS_TAG released from $TRAVIS_REPO_SLUG 
              Released on successful build on Travis CI via deployment contains the
              - iOS APK unsigned for testing
              - Android unsigned APK for testing
              *Build initated from $TRAVIS_COMMIT*
              #### Feature Releases
              - Improve the CI Features
              #### Bug Fixes
              - Fixed the yml files for travis
              - Fixed the yml files for appveyor"
        draft: false
        keep-history: true
        on:
          branch: master
          tags: false
  
    
notifications:
  email: false
 
#end
