#lets see how this works | creates to build jobs 
matrix:
  include:
    #android app 
    - language: generic
      node_js:
        - 6.9.1
      sudo: true
      branches:
        only:
          - master
      install:
        - sudo apt-get install npm
        - cd quiz-master
        - sudo npm install -g n
        - sudo n stable
        #- sudo npm install
        - sudo npm install electron-builder --save-dev
      script:
        #- sudo cordova prepare
        - npm run dist
        - ls
        - cd dist
      release:
        - exit 0
  
    
notifications:
  email: false
 
#end
